---
apiVersion: v1
kind: Pod

metadata:
  name: anita
  labels:
    app: anita

spec:
  containers:
    - command:
      - "sh"
      - "-c"
      - "npm start"
      name: anita
      image: asiancawfee/anita:latest
      imagePullPolicy: Always
      volumeMounts:
        - name : env
          mountPath: /app/.env
  volumes:
    - name: env
      hostPath:
        path: /home/ubuntu/git_project/Anita-VA-Discord-JS/.env

